### ISSUE TITLE
B2Context.java fails calculating getVersionNumber

### ISSUE THREAD

**Issue by gihernandez** [celtic-project/bb-b2context#1]
https://github.com/celtic-project/bb-b2context/blob/master/src/com/spvsoftwareproducts/blackboard/utils/B2Context.java#L2953

The method getVersionNumber generates a _**ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3**_, I was going thru the method and find out that this other method:

```
public static String getVersionNumber(String defaultValue) {

    return ConfigurationServiceFactory.getInstance().getBbProperty(BbConfig.VERSION_NUMBER, defaultValue);

  }
```

Retrieves the version formatted this way:    0.0.0+00000   so when the getVersionNumber method split this string this way `String[] sVersion = version.split("\\.");`  only generates an array with size 3 causing a OOB on line 2966.

**Comment by spvickers** [comment]
What version of Learn are you using?  That is, what is the value being returned by getVersionNumber(String defaultValue) on your system?  Thanks.

**Comment by gihernandez** [comment]
Hi, @spvickers after more testing I find out that it was a different configuration on my application. So the issue is not happening again, now it fails in other place but I think is already solved with this commit 263d01, thanks!!
