### ISSUE TITLE
The processCourseExport method causing auto-archive to fail on Blackboard SaaS systems

### ISSUE THREAD

**Issue by jbaxe2** [celtic-project/bb-b2context#2]
Hello,
We are making use of the Basic LTI building block, which makes use of this library.  We are a client of Blackboard on their SaaS deployment, which makes use of an auto-archive feature of courses during particular times.  One of those times is when a course is about to be deleted.

There is an error when the Basic LTI building block attempts to perform its part of the auto-archive process (stack trace listed below).  The error actually resides in a line of code from this library, referenced here:

https://github.com/celtic-project/bb-b2context/blob/master/src/com/spvsoftwareproducts/blackboard/utils/B2Context.java#L2878

The line in question is:

`settings.put(className + "." + GROUPS_SETTING, sb.substring(1));`

That sb string is apparently empty, and does not contain an index of 1, triggering an error.

Due to the error, the auto-archive process fails, which in turn causes our courses to be unable to be deleted.  One of the kickers is that the courses we're attempting to delete aren't even using the Basic LTI building block.  And the other kicker is that Blackboard states this is all working as designed.

Please let me know if there's any other information you may need about this issue.

----------------------------------
Stack trace:

> Dec 10, 2020 11:45:33 AM - [INFORMATION] Information: Exporting Basic LTI tools instances
> Dec 10, 2020 11:45:34 AM - [ERROR] Error: An unexpected error occurred during Basic LTI tools processing.
> 	For more information, consult the detailed log.
> Dec 10, 2020 11:45:34 AM - [DEBUG] Debug: java.lang.StringIndexOutOfBoundsException: start 1, end 0, length 0
> 	at java.base/java.lang.AbstractStringBuilder.checkRangeSIOOBE(AbstractStringBuilder.java:1724)
> 	at java.base/java.lang.AbstractStringBuilder.substring(AbstractStringBuilder.java:1017)
> 	at java.base/java.lang.StringBuilder.substring(StringBuilder.java:85)
> 	at java.base/java.lang.AbstractStringBuilder.substring(AbstractStringBuilder.java:968)
> 	at java.base/java.lang.StringBuilder.substring(StringBuilder.java:85)
> 	at com.spvsoftwareproducts.blackboard.utils.B2Context.processCourseExport(B2Context.java:2878)
> 	at org.oscelot.blackboard.utils.OscBasicLTICxComponent.doExport(OscBasicLTICxComponent.java:242)
> 	at jdk.internal.reflect.GeneratedMethodAccessor6249.invoke(Unknown Source)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
> 	at blackboard.platform.extension.impl.ExtensionProxyFactory$ExtensionInvocationHandler.lambda$invoke$0(ExtensionProxyFactory.java:188)
> 	at blackboard.util.ThreadUtil.lambda$callWithContextClassLoader$0(ThreadUtil.java:167)
> 	at java.base/java.security.AccessController.doPrivileged(Native Method)
> 	at blackboard.util.ThreadUtil.callWithContextClassLoader(ThreadUtil.java:163)
> 	at blackboard.util.ThreadUtil.callWithContextClassLoader(ThreadUtil.java:128)
> 	at blackboard.platform.plugin.PlugInUtilEx.callWithCurrentPlugInAndContextClassLoader(PlugInUtilEx.java:133)
> 	at blackboard.platform.extension.impl.ExtensionProxyFactory$ExtensionInvocationHandler.invoke(ExtensionProxyFactory.java:188)
> 	at com.sun.proxy.$Proxy2346.doExport(Unknown Source)
> 	at blackboard.apps.cx.Exporter.exportGenericPackageEntries(Exporter.java:2222)
> 	at blackboard.apps.cx.Exporter.execute(Exporter.java:254)
> 	at blackboard.apps.cx.Cx.invoke(Cx.java:382)
> 	at blackboard.apps.cx.BaseCxQueuedOperation.execute(BaseCxQueuedOperation.java:108)
> 	at blackboard.apps.cx.autoarchive.AutoArchiveQueuedOperation.execute(AutoArchiveQueuedOperation.java:79)
> 	at blackboard.apps.platform.course.CourseDeleteQueuedOperation.executeAutoArchive(CourseDeleteQueuedOperation.java:224)
> 	at blackboard.apps.platform.course.CourseDeleteQueuedOperation.lambda$execute$0(CourseDeleteQueuedOperation.java:125)
> 	at blackboard.persist.IgnoreRowStatusContextManager.set(IgnoreRowStatusContextManager.java:94)
> 	at blackboard.apps.platform.course.CourseDeleteQueuedOperation.execute(CourseDeleteQueuedOperation.java:124)
> 	at blackboard.platform.queue.QueuedTaskManager.processTask(QueuedTaskManager.java:457)
> 	at blackboard.platform.queue.QueuedTaskManager$WorkerThread.doRun(QueuedTaskManager.java:899)
> 	at blackboard.db.LeakCheckThread.run(LeakCheckThread.java:38)

**Comment by oijusti** [comment]
@jbaxe2 This error occurs when the Course does not have any Group. As a workaround, try creating a group and execute the archiving process again.

**Comment by jbaxe2** [comment]
Creating a group did allow the auto-archive to work, and the course deleted.  That said, this library should not depend on whether a course has a group in it, in order to work properly.  Most courses don't.

**Comment by spvickers** [comment]
Fixed in 1.9.01 release.  Thanks.

**Comment by jbaxe2** [comment]
Thanks for updating this, and the Basic LTI building block as well!
